"""add payments and payment shares

Revision ID: 4ab22638ad2c
Revises: e45b8e6ab433
Create Date: 2026-09-21 12:51:23.782093

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '4ab22638ad2c'
down_revision: str | Sequence[str] | None = 'e45b8e6ab433'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
