"""add idempotency records

Revision ID: 686f8285d015
Revises: a5b88ab59ff5
Create Date: 2026-09-21 14:15:53.155808

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '686f8285d015'
down_revision: str | Sequence[str] | None = 'a5b88ab59ff5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=20), server_default=sa.text("'IN_PROGRESS'"), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('IN_PROGRESS', 'COMPLETED')", name=op.f('ck_idempotency_records_state_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_records_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('user_id', 'operation', 'idempotency_key', name='uq_idempotency_user_operation_key')
    )
    op.create_index('ix_idempotency_expires_at', 'idempotency_records', ['expires_at'], unique=False)
    op.create_index('ix_idempotency_user_created_at', 'idempotency_records', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_idempotency_user_created_at', table_name='idempotency_records')
    op.drop_index('ix_idempotency_expires_at', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
