"""add settlements

Revision ID: a5b88ab59ff5
Revises: e45b8e6ab433
Create Date: 2026-09-21 13:49:41.994139

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5b88ab59ff5'
down_revision: str | Sequence[str] | None = 'e45b8e6ab433'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.String(length=250), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'ACTIVE'\n                AND voided_at IS NULL\n                AND voided_by_user_id IS NULL\n            )\n            OR\n            (\n                status = 'VOIDED'\n                AND voided_at IS NOT NULL\n                AND voided_by_user_id IS NOT NULL\n            )\n            ", name=op.f('ck_settlements_void_state_consistent')),
    sa.CheckConstraint("method IN ('CASH', 'UPI', 'OTHER')", name=op.f('ck_settlements_method_valid')),
    sa.CheckConstraint("status IN ('ACTIVE', 'VOIDED')", name=op.f('ck_settlements_status_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_settlements_amount_positive')),
    sa.CheckConstraint('from_user_id <> to_user_id', name=op.f('ck_settlements_different_users')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_settlements_from_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_settlements_to_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], name=op.f('fk_settlements_voided_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_index('ix_settlements_from_to_created_at', 'settlements', ['from_user_id', 'to_user_id', 'created_at'], unique=False)
    op.create_index('ix_settlements_status', 'settlements', ['status'], unique=False)
    op.create_index('ix_settlements_to_from_created_at', 'settlements', ['to_user_id', 'from_user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settlements_to_from_created_at', table_name='settlements')
    op.drop_index('ix_settlements_status', table_name='settlements')
    op.drop_index('ix_settlements_from_to_created_at', table_name='settlements')
    op.drop_table('settlements')
    # ### end Alembic commands ###
