"""create core session tables

Revision ID: bb0568f2fb3d
Revises: 
Create Date: 2026-09-20 22:20:07.407815

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bb0568f2fb3d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('username_normalized', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name=op.f('ck_users_status_valid')),
    sa.CheckConstraint('length(btrim(display_name)) > 0', name=op.f('ck_users_display_name_not_blank')),
    sa.CheckConstraint('length(btrim(username_normalized)) > 0', name=op.f('ck_users_username_normalized_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username_normalized', name=op.f('uq_users_username_normalized'))
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('join_code', sa.String(length=8), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'ACTIVE' AND closed_at IS NULL) OR (status = 'CLOSED' AND closed_at IS NOT NULL)", name=op.f('ck_sessions_status_closed_at_consistent')),
    sa.CheckConstraint("status IN ('ACTIVE', 'CLOSED')", name=op.f('ck_sessions_status_valid')),
    sa.CheckConstraint('name IS NULL OR length(btrim(name)) > 0', name=op.f('ck_sessions_name_not_blank')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_sessions_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('join_code', name=op.f('uq_sessions_join_code'))
    )
    op.create_index('ix_sessions_created_at', 'sessions', ['created_at'], unique=False)
    op.create_index('ix_sessions_status', 'sessions', ['status'], unique=False)
    op.create_table('session_participations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('left_at IS NULL OR left_at > joined_at', name=op.f('ck_session_participations_left_after_join')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_participations_session_id_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_participations_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_participations'))
    )
    op.create_index('ix_session_participations_session_joined', 'session_participations', ['session_id', 'joined_at'], unique=False)
    op.create_index('ix_session_participations_user_joined', 'session_participations', ['user_id', 'joined_at'], unique=False)
    op.create_index('uq_session_participations_active_user', 'session_participations', ['session_id', 'user_id'], unique=True, postgresql_where=sa.text('left_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_session_participations_active_user', table_name='session_participations', postgresql_where=sa.text('left_at IS NULL'))
    op.drop_index('ix_session_participations_user_joined', table_name='session_participations')
    op.drop_index('ix_session_participations_session_joined', table_name='session_participations')
    op.drop_table('session_participations')
    op.drop_index('ix_sessions_status', table_name='sessions')
    op.drop_index('ix_sessions_created_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
