"""add payments and payment shares

Revision ID: e45b8e6ab433
Revises: 0f4d17950675
Create Date: 2026-09-21 02:10:48.069974

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e45b8e6ab433'
down_revision: str | Sequence[str] | None = '0f4d17950675'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('payer_user_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('total_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('split_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('corrected_from_payment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('void_reason', sa.String(length=250), nullable=True),
    sa.CheckConstraint("(status = 'ACTIVE' AND voided_at IS NULL AND voided_by_user_id IS NULL) OR (status = 'VOIDED' AND voided_at IS NOT NULL AND voided_by_user_id IS NOT NULL)", name=op.f('ck_payments_void_state_consistent')),
    sa.CheckConstraint("split_type IN ('EQUAL', 'CUSTOM')", name=op.f('ck_payments_split_type_valid')),
    sa.CheckConstraint("status IN ('ACTIVE', 'VOIDED')", name=op.f('ck_payments_status_valid')),
    sa.CheckConstraint('total_amount_minor > 0', name=op.f('ck_payments_total_amount_positive')),
    sa.ForeignKeyConstraint(['corrected_from_payment_id'], ['payments.id'], name=op.f('fk_payments_corrected_from_payment_id_payments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], name=op.f('fk_payments_payer_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_payments_session_id_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], name=op.f('fk_payments_voided_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_corrected_from', 'payments', ['corrected_from_payment_id'], unique=False)
    op.create_index('ix_payments_payer_created_at', 'payments', ['payer_user_id', 'created_at'], unique=False)
    op.create_index('ix_payments_session_created_at', 'payments', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_table('payment_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_payment_shares_amount_positive')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_shares_payment_id_payments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_shares_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_shares')),
    sa.UniqueConstraint('payment_id', 'user_id', name='uq_payment_shares_payment_user')
    )
    op.create_index('ix_payment_shares_payment_id', 'payment_shares', ['payment_id'], unique=False)
    op.create_index('ix_payment_shares_user_id', 'payment_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_shares_user_id', table_name='payment_shares')
    op.drop_index('ix_payment_shares_payment_id', table_name='payment_shares')
    op.drop_table('payment_shares')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_session_created_at', table_name='payments')
    op.drop_index('ix_payments_payer_created_at', table_name='payments')
    op.drop_index('ix_payments_corrected_from', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
